@SneakerCollection.API_HostAddress = http://localhost:5067
@userId = ab6c775d-0106-4171-87a5-141628190079
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNTA2OGZjYS03NTkxLTRmOGUtYWJjYy01NWZkOGUwZTAwOGYiLCJnaXZlbl9uYW1lIjoiR2FicmllbGxhIiwiZmFtaWx5X25hbWUiOiJDb2VsaG8gZGUgQW5kcmFkZSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwianRpIjoiOGMyZTE5NDYtNGNiYS00OGQ5LWE2ZTMtYzJmZjJlMTMwM2M4IiwiZXhwIjoxNzA4OTA4NzA3LCJpc3MiOiJTbmVha2VyQ29sbGVjdGlvbiIsImF1ZCI6IlNuZWFrZXJDb2xsZWN0aW9uIn0.IOFlmVzjLMksRK3zMZbBgf0andrDao2n42JfnUl_IT0

POST {{SneakerCollection.API_HostAddress}}/sneakers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Air jordan",
    "brand":
    {
        "name": "Nike"
    },
    "price":
    {
        "currency": "$",
        "amount": 230
    },
    "sizeUS": 11.5,
    "year": 2018,
    "rate": 4
}

###
