@SneakerCollection.API_HostAddress = http://localhost:5067
@token = <write_your_token_here>

POST {{SneakerCollection.API_HostAddress}}/sneakers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Air jordan",
    "brand":
    {
        "name": "Nike"
    },
    "price":
    {
        "currency": "$",
        "amount": 230
    },
    "sizeUS": 11.5,
    "year": 2018,
    "rate": 4
}

###

POST {{SneakerCollection.API_HostAddress}}/sneakers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Forum Low",
    "brand":
    {
        "name": "Adidas"
    },
    "price":
    {
        "currency": "$",
        "amount": 100
    },
    "sizeUS": 11,
    "year": 2020,
    "rate": 5
}

###