@SneakerCollection.API_HostAddress = http://localhost:5067
@userId = ab6c775d-0106-4171-87a5-141628190079
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZWIzMDdkNC1lMTY5LTQwN2YtOTdiZi00ZGIzZDcwMzQ5YzciLCJnaXZlbl9uYW1lIjoiUmVuYW4iLCJmYW1pbHlfbmFtZSI6IkZlcm5hbmRlcyBTaWx2YSIsImVtYWlsIjoicmVuYW5mc3NpbHZhQGdtYWlsLmNvbSIsImp0aSI6ImEwMGJmOTQ5LWFkYWYtNGFmNS04NjRmLTIwY2I1OTk1ZTVhNyIsImV4cCI6MTcwODkxMDAyNSwiaXNzIjoiU25lYWtlckNvbGxlY3Rpb24iLCJhdWQiOiJTbmVha2VyQ29sbGVjdGlvbiJ9.MQm0IrP-LmoOfebxGRlAaQpGATMWrCp9UvCYOYqs6UQ

POST {{SneakerCollection.API_HostAddress}}/sneakers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Air jordan",
    "brand":
    {
        "name": "Nike"
    },
    "price":
    {
        "currency": "$",
        "amount": 230
    },
    "sizeUS": 11.5,
    "year": 2018,
    "rate": 4
}

###
