@SneakerCollection.API_HostAddress = http://localhost:5067
@SneakerId = 90228718-4fc4-4cbc-9e93-1a2cbde61e94
@token = <write_your_token_here>

DELETE {{SneakerCollection.API_HostAddress}}/sneakers/{{SneakerId}}
Authorization: Bearer {{token}}

###
