@SneakerCollection.API_HostAddress = http://localhost:5067
@SneakerId = 90228718-4fc4-4cbc-9e93-1a2cbde61e94
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNmE4NGYwOC03NzVhLTRhOGEtOTQ0Yi01YWM3N2Y4MThlZDgiLCJnaXZlbl9uYW1lIjoiUmVuYW4iLCJmYW1pbHlfbmFtZSI6IkZlcm5hbmRlcyBTaWx2YSIsImVtYWlsIjoicmVuYW5mc3NpbHZhQGdtYWlsLmNvbSIsImp0aSI6IjViNjdlMjQzLTJiZjUtNDIxNi04MTQ5LWVkYjEwYzk3MTdlYyIsImV4cCI6MTcwODk3MzE3MiwiaXNzIjoiU25lYWtlckNvbGxlY3Rpb24iLCJhdWQiOiJTbmVha2VyQ29sbGVjdGlvbiJ9.Q3uWVEGy37VripX5ki4PRHgiW2Vn04bPIzTmxRGpvzc

DELETE {{SneakerCollection.API_HostAddress}}/sneakers/{{SneakerId}}
Authorization: Bearer {{token}}

###
