@SneakerId = 953fc5b9-9f5b-44f4-b811-6d794b895294
@SneakerCollection.API_HostAddress = http://localhost:5067

GET {{SneakerCollection.API_HostAddress}}/sneakers/{{SneakerId}}
Authorization: Bearer <write_your_token_here>

###
