@SneakerCollection.API_HostAddress = http://localhost:5067
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNmE4NGYwOC03NzVhLTRhOGEtOTQ0Yi01YWM3N2Y4MThlZDgiLCJnaXZlbl9uYW1lIjoiUmVuYW4iLCJmYW1pbHlfbmFtZSI6IkZlcm5hbmRlcyBTaWx2YSIsImVtYWlsIjoicmVuYW5mc3NpbHZhQGdtYWlsLmNvbSIsImp0aSI6ImIxMzI0M2ExLTk2ZDMtNGVmMi04MGQ0LWE5MDVhNWI2MmRiYSIsImV4cCI6MTcwOTA1NTE0MCwiaXNzIjoiU25lYWtlckNvbGxlY3Rpb24iLCJhdWQiOiJTbmVha2VyQ29sbGVjdGlvbiJ9.KtnRIBA_aUCBD8dZw_v4MUk4NeTMFu1-T4Gms4e9O3Q

GET {{SneakerCollection.API_HostAddress}}/sneakers
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?searchTerm=nike
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=year&sortOrder=desc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=size_us&sortOrder=asc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=amount&sortOrder=desc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=currency&sortOrder=desc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?page=1&pageSize=-1
Authorization: Bearer {{token}}

###