@SneakerCollection.API_HostAddress = http://localhost:5067

GET {{SneakerCollection.API_HostAddress}}/sneakers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZWIzMDdkNC1lMTY5LTQwN2YtOTdiZi00ZGIzZDcwMzQ5YzciLCJnaXZlbl9uYW1lIjoiUmVuYW4iLCJmYW1pbHlfbmFtZSI6IkZlcm5hbmRlcyBTaWx2YSIsImVtYWlsIjoicmVuYW5mc3NpbHZhQGdtYWlsLmNvbSIsImp0aSI6ImEwMGJmOTQ5LWFkYWYtNGFmNS04NjRmLTIwY2I1OTk1ZTVhNyIsImV4cCI6MTcwODkxMDAyNSwiaXNzIjoiU25lYWtlckNvbGxlY3Rpb24iLCJhdWQiOiJTbmVha2VyQ29sbGVjdGlvbiJ9.MQm0IrP-LmoOfebxGRlAaQpGATMWrCp9UvCYOYqs6UQ

###
