@SneakerCollection.API_HostAddress = http://localhost:5067
@token = <write_your_token_here>

GET {{SneakerCollection.API_HostAddress}}/sneakers
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?searchTerm=nike
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=year&sortOrder=desc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=size_us&sortOrder=asc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=amount&sortOrder=desc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?sortColumn=currency&sortOrder=desc
Authorization: Bearer {{token}}

###

GET {{SneakerCollection.API_HostAddress}}/sneakers?page=1&pageSize=-1
Authorization: Bearer {{token}}

###