@SneakerCollection.API_HostAddress = http://localhost:5067
@SneakerId = 953fc5b9-9f5b-44f4-b811-6d794b895294
@token = <write_your_token_here>

PATCH {{SneakerCollection.API_HostAddress}}/sneakers/{{SneakerId}}
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

[
    { "op": "replace", "path": "/Year", "value": 2021 },
    { "op": "replace", "path": "/Rate", "value": 1 }
]

###
