@SneakerCollection.API_HostAddress = http://localhost:5067
@SneakerId = 953fc5b9-9f5b-44f4-b811-6d794b895294
@token = <write_your_token_here>

PUT {{SneakerCollection.API_HostAddress}}/sneakers/{{SneakerId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Air jordan Updated",
    "brand":
    {
        "name": "Nike"
    },
    "price":
    {
        "currency": "$",
        "amount": 230
    },
    "sizeUS": 11.5,
    "year": 2018,
    "rate": 4
}

###
